global:
  scrape_interval:     3s
  evaluation_interval: 15s
  external_labels:
    monitor: 'example-app'


scrape_configs:
  - job_name: 'education'
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['educationms:8081']

  - job_name: 'marketplace'
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['marketplacems:8082']

  - job_name: 'membership'
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['membershipms:8083']